INSERT INTO asset_db.asset (name, owner, description, location, criticality) values ('Dialog 676015', 'Bob', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Critical'),
('Samsung 201945', 'Bob', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Medium'),
('Samsung 60646', 'Bob', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Low'),
('Asuz 12894', 'Bob', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Critical'),
('Dialog 765012', 'Bob', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Medium'),
('Asuz 691084', 'Bob', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Low'),
('Asuz 531466', 'Bob', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Critical'),
('Samsung 371007', 'Bob', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Medium'),
('Dialog 852178', 'Bob', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Low'),
('Dialog 439205', 'Bob', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Critical'),
('Cisco 450065', 'Bob', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Medium'),
('Dialog 702538', 'Bob', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Low'),
('Samsung 163800', 'Bob', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Critical'),
('Asuz 653946', 'Bob', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Medium'),
('Cisco 239718', 'Bob', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Low'),
('Cisco 647535', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Critical'),
('Samsung 118099', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Medium'),
('Samsung 494873', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Low'),
('Asuz 945853', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Critical'),
('Samsung 305926', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Medium'),
('Samsung 835971', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Low'),
('Asuz 527979', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Critical'),
('Samsung 542148', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Medium'),
('Asuz 86526', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Low'),
('Dialog 265845', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Critical'),
('Cisco 208791', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Medium'),
('Dialog 477549', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Low'),
('Asuz 359118', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Critical'),
('Samsung 381108', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Medium'),
('Dialog 935087', 'Bob', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Low'),
('Dialog 92038', 'Bob', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Critical'),
('Cisco 920457', 'Bob', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Medium'),
('Samsung 361915', 'Bob', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Low'),
('Asuz 972856', 'Bob', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Critical'),
('Cisco 721160', 'Bob', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Medium'),
('Samsung 140641', 'Bob', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Low'),
('Asuz 38426', 'Bob', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Critical'),
('Dialog 93142', 'Bob', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Medium'),
('Cisco 488858', 'Bob', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Low'),
('Dialog 742547', 'Bob', '1 Internal Services1 Internal Services Module slot', 'basement', 'Critical'),
('Dialog 105135', 'Bob', '1 Internal Services1 Internal Services Module slot', 'basement', 'Medium'),
('Dialog 347989', 'Bob', '1 Internal Services1 Internal Services Module slot', 'basement', 'Low'),
('Samsung 287083', 'Bob', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Critical'),
('Dialog 841463', 'Bob', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Medium'),
('Asuz 483124', 'Bob', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Low'),
('Samsung 131861', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Critical'),
('Samsung 992733', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Medium'),
('Asuz 758263', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Low'),
('Asuz 995512', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Critical'),
('Asuz 448055', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Medium'),
('Asuz 21052', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Low'),
('Dialog 951619', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Critical'),
('Dialog 420180', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Medium'),
('Cisco 47479', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Low'),
('Samsung 536550', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Critical'),
('Cisco 758412', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Medium'),
('Asuz 489476', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Low'),
('Cisco 108030', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Critical'),
('Cisco 618049', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Medium'),
('Dialog 619474', 'Bob', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Low'),
('Asuz 697004', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Critical'),
('Dialog 211941', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Medium'),
('Samsung 444804', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Low'),
('Dialog 238017', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Critical'),
('Cisco 928067', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Medium'),
('Dialog 840485', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Low'),
('Dialog 467633', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Critical'),
('Cisco 177051', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Medium'),
('Dialog 411162', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Low'),
('Dialog 309682', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Critical'),
('Samsung 976861', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Medium'),
('Dialog 576308', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Low'),
('Samsung 797520', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Critical'),
('Asuz 133707', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Medium'),
('Samsung 505824', 'Bob', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Low'),
('Samsung 376313', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Critical'),
('Asuz 577800', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Medium'),
('Asuz 667354', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Low'),
('Samsung 339773', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Critical'),
('Asuz 244258', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Medium'),
('Cisco 169423', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Low'),
('Asuz 459470', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Critical'),
('Cisco 292436', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Medium'),
('Cisco 491894', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Low'),
('Cisco 330320', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Critical'),
('Cisco 426384', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Medium'),
('Samsung 690191', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Low'),
('Samsung 579403', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Critical'),
('Dialog 796890', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Medium'),
('Asuz 979046', 'Bob', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Low'),
('Asuz 401527', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Critical'),
('Dialog 794404', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Medium'),
('Samsung 767668', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Low'),
('Asuz 188677', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Critical'),
('Samsung 115621', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Medium'),
('Cisco 529644', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Low'),
('Dialog 880375', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Critical'),
('Samsung 118387', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Medium'),
('Cisco 518572', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Low'),
('Dialog 939799', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Critical'),
('Dialog 390358', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Medium'),
('Samsung 466939', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Low'),
('Asuz 382062', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Critical'),
('Samsung 965797', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Medium'),
('Dialog 330310', 'Bob', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Low'),
('Cisco 644690', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Critical'),
('Cisco 366908', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Medium'),
('Cisco 706536', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Low'),
('Asuz 258715', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Critical'),
('Dialog 225157', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Medium'),
('Asuz 631037', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Low'),
('Samsung 191369', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Critical'),
('Asuz 678294', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Medium'),
('Samsung 72968', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Low'),
('Asuz 886443', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Critical'),
('Asuz 721944', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Medium'),
('Samsung 927164', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Low'),
('Samsung 927410', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Critical'),
('Asuz 589388', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Medium'),
('Asuz 412215', 'Bob', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Low'),
('Samsung 273400', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Critical'),
('Cisco 643660', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Medium'),
('Asuz 844751', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Low'),
('Asuz 419615', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Critical'),
('Cisco 627551', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Medium'),
('Asuz 448122', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Low'),
('Dialog 39308', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Critical'),
('Samsung 893188', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Medium'),
('Samsung 246656', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Low'),
('Dialog 496424', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Critical'),
('Asuz 619700', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Medium'),
('Dialog 914940', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Low'),
('Cisco 474181', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Critical'),
('Asuz 520399', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Medium'),
('Asuz 730328', 'Kamala', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Low'),
('Cisco 298049', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Critical'),
('Asuz 701475', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Medium'),
('Asuz 4812', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Low'),
('Dialog 994842', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Critical'),
('Samsung 736526', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Medium'),
('Dialog 765577', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Low'),
('Samsung 424943', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Critical'),
('Cisco 621249', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Medium'),
('Samsung 662652', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Low'),
('Samsung 527604', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Critical'),
('Cisco 770419', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Medium'),
('Cisco 483951', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Low'),
('Samsung 733029', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Critical'),
('Asuz 28254', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Medium'),
('Dialog 102121', 'Kamala', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Low'),
('Asuz 458630', 'Kamala', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Critical'),
('Samsung 57537', 'Kamala', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Medium'),
('Asuz 954418', 'Kamala', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Low'),
('Dialog 453172', 'Kamala', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Critical'),
('Cisco 619814', 'Kamala', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Medium'),
('Samsung 996534', 'Kamala', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Low'),
('Dialog 404370', 'Kamala', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Critical'),
('Asuz 667036', 'Kamala', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Medium'),
('Asuz 438076', 'Kamala', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Low'),
('Dialog 95006', 'Kamala', '1 Internal Services1 Internal Services Module slot', 'basement', 'Critical'),
('Dialog 725014', 'Kamala', '1 Internal Services1 Internal Services Module slot', 'basement', 'Medium'),
('Asuz 553042', 'Kamala', '1 Internal Services1 Internal Services Module slot', 'basement', 'Low'),
('Cisco 601147', 'Kamala', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Critical'),
('Cisco 31445', 'Kamala', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Medium'),
('Dialog 620981', 'Kamala', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Low'),
('Asuz 927528', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Critical'),
('Asuz 29897', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Medium'),
('Samsung 629353', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Low'),
('Cisco 852414', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Critical'),
('Dialog 444788', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Medium'),
('Asuz 837209', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Low'),
('Dialog 172213', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Critical'),
('Cisco 329803', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Medium'),
('Asuz 770192', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Low'),
('Cisco 409744', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Critical'),
('Dialog 245003', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Medium'),
('Asuz 29450', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Low'),
('Cisco 400526', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Critical'),
('Dialog 772012', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Medium'),
('Asuz 257082', 'Kamala', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Low'),
('Asuz 436406', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Critical'),
('Cisco 332608', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Medium'),
('Cisco 621596', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Low'),
('Dialog 955180', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Critical'),
('Asuz 175355', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Medium'),
('Asuz 773178', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Low'),
('Asuz 535405', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Critical'),
('Dialog 212485', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Medium'),
('Cisco 193993', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Low'),
('Asuz 581339', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Critical'),
('Dialog 196196', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Medium'),
('Dialog 59546', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Low'),
('Asuz 747184', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Critical'),
('Asuz 754631', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Medium'),
('Samsung 894234', 'Kamala', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Low'),
('Samsung 188735', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Critical'),
('Cisco 728862', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Medium'),
('Asuz 873197', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Low'),
('Asuz 639151', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Critical'),
('Asuz 506224', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Medium'),
('Samsung 364077', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Low'),
('Asuz 656628', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Critical'),
('Dialog 192780', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Medium'),
('Asuz 447350', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Low'),
('Dialog 558765', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Critical'),
('Cisco 955593', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Medium'),
('Samsung 740344', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Low'),
('Dialog 767341', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Critical'),
('Dialog 184287', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Medium'),
('Cisco 586572', 'Kamala', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Low'),
('Cisco 423478', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Critical'),
('Cisco 574971', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Medium'),
('Cisco 136405', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Low'),
('Asuz 389277', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Critical'),
('Asuz 404730', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Medium'),
('Asuz 915070', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Low'),
('Cisco 647478', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Critical'),
('Asuz 831925', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Medium'),
('Cisco 231815', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Low'),
('Dialog 795477', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Critical'),
('Cisco 108388', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Medium'),
('Cisco 578765', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Low'),
('Cisco 230697', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Critical'),
('Asuz 97378', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Medium'),
('Dialog 475182', 'Kamala', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Low'),
('Dialog 26917', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Critical'),
('Dialog 783258', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Medium'),
('Samsung 374278', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Low'),
('Asuz 460862', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Critical'),
('Asuz 978916', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Medium'),
('Cisco 280831', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Low'),
('Asuz 960379', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Critical'),
('Asuz 683729', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Medium'),
('Samsung 972670', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Low'),
('Cisco 481417', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Critical'),
('Asuz 447340', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Medium'),
('Asuz 43366', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Low'),
('Dialog 898346', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Critical'),
('Cisco 828174', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Medium'),
('Asuz 271689', 'Kamala', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Low'),
('Dialog 769928', 'Saman', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Critical'),
('Samsung 874703', 'Saman', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Medium'),
('Samsung 685038', 'Saman', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Low'),
('Samsung 626189', 'Saman', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Critical'),
('Samsung 149071', 'Saman', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Medium'),
('Cisco 900038', 'Saman', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Low'),
('Samsung 167345', 'Saman', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Critical'),
('Asuz 651029', 'Saman', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Medium'),
('Cisco 584083', 'Saman', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Low'),
('Cisco 352526', 'Saman', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Critical'),
('Cisco 36130', 'Saman', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Medium'),
('Samsung 646189', 'Saman', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Low'),
('Samsung 127801', 'Saman', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Critical'),
('Dialog 945485', 'Saman', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Medium'),
('Dialog 241007', 'Saman', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Low'),
('Cisco 781322', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Critical'),
('Dialog 569562', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Medium'),
('Cisco 553196', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Low'),
('Asuz 312440', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Critical'),
('Cisco 302895', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Medium'),
('Cisco 231922', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Low'),
('Dialog 805634', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Critical'),
('Asuz 6880', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Medium'),
('Samsung 397982', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Low'),
('Cisco 365142', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Critical'),
('Samsung 138119', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Medium'),
('Asuz 167460', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Low'),
('Cisco 28735', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Critical'),
('Samsung 735922', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Medium'),
('Asuz 294890', 'Saman', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Low'),
('Cisco 668329', 'Saman', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Critical'),
('Cisco 421268', 'Saman', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Medium'),
('Dialog 623714', 'Saman', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Low'),
('Asuz 959146', 'Saman', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Critical'),
('Samsung 298570', 'Saman', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Medium'),
('Samsung 324300', 'Saman', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Low'),
('Cisco 658626', 'Saman', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Critical'),
('Samsung 86183', 'Saman', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Medium'),
('Asuz 804109', 'Saman', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Low'),
('Asuz 472580', 'Saman', '1 Internal Services1 Internal Services Module slot', 'basement', 'Critical'),
('Dialog 840099', 'Saman', '1 Internal Services1 Internal Services Module slot', 'basement', 'Medium'),
('Samsung 966786', 'Saman', '1 Internal Services1 Internal Services Module slot', 'basement', 'Low'),
('Asuz 96731', 'Saman', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Critical'),
('Cisco 635354', 'Saman', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Medium'),
('Asuz 149858', 'Saman', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Low'),
('Asuz 531279', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Critical'),
('Dialog 494980', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Medium'),
('Asuz 310688', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Low'),
('Cisco 825016', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Critical'),
('Asuz 971964', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Medium'),
('Samsung 823376', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Low'),
('Dialog 399427', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Critical'),
('Samsung 529229', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Medium'),
('Samsung 353342', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Low'),
('Cisco 534743', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Critical'),
('Cisco 277662', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Medium'),
('Dialog 620494', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Low'),
('Cisco 696636', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Critical'),
('Dialog 398019', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Medium'),
('Asuz 481241', 'Saman', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Low'),
('Cisco 720622', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Critical'),
('Samsung 657006', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Medium'),
('Asuz 527564', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Low'),
('Asuz 488122', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Critical'),
('Asuz 931260', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Medium'),
('Cisco 816067', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Low'),
('Asuz 565069', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Critical'),
('Samsung 147630', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Medium'),
('Cisco 181485', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Low'),
('Cisco 559759', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Critical'),
('Cisco 131599', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Medium'),
('Dialog 804840', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Low'),
('Cisco 949731', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Critical'),
('Samsung 890965', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Medium'),
('Dialog 196241', 'Saman', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Low'),
('Dialog 670742', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Critical'),
('Asuz 634734', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Medium'),
('Samsung 4181', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Low'),
('Dialog 457844', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Critical'),
('Dialog 233723', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Medium'),
('Samsung 925813', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Low'),
('Asuz 183189', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Critical'),
('Dialog 223546', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Medium'),
('Dialog 784398', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Low'),
('Samsung 624749', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Critical'),
('Asuz 447497', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Medium'),
('Asuz 289193', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Low'),
('Cisco 281232', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Critical'),
('Asuz 533173', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Medium'),
('Asuz 815347', 'Saman', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Low'),
('Cisco 223652', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Critical'),
('Asuz 280265', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Medium'),
('Dialog 991454', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Low'),
('Asuz 806542', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Critical'),
('Dialog 921764', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Medium'),
('Dialog 461516', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Low'),
('Dialog 509520', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Critical'),
('Cisco 524853', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Medium'),
('Dialog 693273', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Low'),
('Asuz 371698', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Critical'),
('Samsung 68645', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Medium'),
('Samsung 572311', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Low'),
('Cisco 391531', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Critical'),
('Asuz 629944', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Medium'),
('Dialog 565249', 'Saman', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Low'),
('Samsung 186987', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Critical'),
('Cisco 322994', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Medium'),
('Dialog 951453', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Low'),
('Dialog 662686', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Critical'),
('Cisco 428578', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Medium'),
('Asuz 545739', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Low'),
('Asuz 81634', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Critical'),
('Asuz 266749', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Medium'),
('Samsung 743209', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Low'),
('Dialog 822874', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Critical'),
('Dialog 277832', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Medium'),
('Dialog 230812', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Low'),
('Cisco 474224', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Critical'),
('Samsung 761345', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Medium'),
('Dialog 455622', 'Saman', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Low'),
('Dialog 451144', 'Alice', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Critical'),
('Cisco 819053', 'Alice', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Medium'),
('Asuz 2253', 'Alice', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Low'),
('Samsung 479', 'Alice', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Critical'),
('Cisco 84438', 'Alice', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Medium'),
('Dialog 694118', 'Alice', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Low'),
('Dialog 634034', 'Alice', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Critical'),
('Samsung 795965', 'Alice', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Medium'),
('Samsung 189808', 'Alice', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Low'),
('Cisco 596128', 'Alice', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Critical'),
('Cisco 341465', 'Alice', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Medium'),
('Asuz 367985', 'Alice', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Low'),
('Samsung 143431', 'Alice', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Critical'),
('Samsung 730751', 'Alice', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Medium'),
('Cisco 646172', 'Alice', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Low'),
('Asuz 750476', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Critical'),
('Dialog 603037', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Medium'),
('Samsung 656689', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Low'),
('Asuz 102692', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Critical'),
('Cisco 773531', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Medium'),
('Dialog 301972', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Low'),
('Asuz 267714', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Critical'),
('Asuz 788148', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Medium'),
('Dialog 185844', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Low'),
('Asuz 373359', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Critical'),
('Asuz 41728', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Medium'),
('Samsung 383184', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Low'),
('Asuz 891438', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Critical'),
('Asuz 381787', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Medium'),
('Cisco 470397', 'Alice', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Low'),
('Dialog 149758', 'Alice', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Critical'),
('Cisco 744839', 'Alice', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Medium'),
('Cisco 311359', 'Alice', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Low'),
('Samsung 330012', 'Alice', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Critical'),
('Cisco 28789', 'Alice', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Medium'),
('Dialog 159885', 'Alice', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Low'),
('Dialog 5094', 'Alice', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Critical'),
('Samsung 35477', 'Alice', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Medium'),
('Samsung 446342', 'Alice', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Low'),
('Samsung 190363', 'Alice', '1 Internal Services1 Internal Services Module slot', 'basement', 'Critical'),
('Dialog 301120', 'Alice', '1 Internal Services1 Internal Services Module slot', 'basement', 'Medium'),
('Dialog 190895', 'Alice', '1 Internal Services1 Internal Services Module slot', 'basement', 'Low'),
('Cisco 422478', 'Alice', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Critical'),
('Dialog 23492', 'Alice', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Medium'),
('Samsung 335633', 'Alice', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Low'),
('Cisco 228426', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Critical'),
('Asuz 447070', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Medium'),
('Cisco 485290', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Low'),
('Samsung 447199', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Critical'),
('Asuz 649487', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Medium'),
('Samsung 703420', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Low'),
('Samsung 611341', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Critical'),
('Dialog 465443', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Medium'),
('Samsung 434398', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Low'),
('Dialog 56904', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Critical'),
('Cisco 821866', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Medium'),
('Samsung 729907', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Low'),
('Samsung 920741', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Critical'),
('Asuz 426401', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Medium'),
('Dialog 632675', 'Alice', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Low'),
('Samsung 484335', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Critical'),
('Cisco 81658', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Medium'),
('Dialog 735038', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Low'),
('Samsung 625744', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Critical'),
('Cisco 523222', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Medium'),
('Samsung 280684', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Low'),
('Dialog 854789', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Critical'),
('Cisco 89607', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Medium'),
('Samsung 453902', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Low'),
('Asuz 560741', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Critical'),
('Samsung 287906', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Medium'),
('Samsung 261730', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Low'),
('Asuz 411610', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Critical'),
('Samsung 49483', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Medium'),
('Dialog 817405', 'Alice', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Low'),
('Dialog 369568', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Critical'),
('Asuz 585804', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Medium'),
('Dialog 317957', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Low'),
('Asuz 465789', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Critical'),
('Cisco 698472', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Medium'),
('Samsung 881850', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Low'),
('Cisco 335837', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Critical'),
('Samsung 714543', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Medium'),
('Dialog 864121', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Low'),
('Cisco 61236', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Critical'),
('Samsung 761773', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Medium'),
('Samsung 847098', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Low'),
('Samsung 537348', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Critical'),
('Dialog 663880', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Medium'),
('Cisco 336644', 'Alice', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Low'),
('Dialog 502323', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Critical'),
('Cisco 575730', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Medium'),
('Asuz 593644', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Low'),
('Asuz 253965', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Critical'),
('Asuz 196278', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Medium'),
('Asuz 743478', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Low'),
('Asuz 991091', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Critical'),
('Cisco 168418', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Medium'),
('Samsung 562388', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Low'),
('Cisco 933841', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Critical'),
('Dialog 766078', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Medium'),
('Samsung 899956', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Low'),
('Cisco 769539', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Critical'),
('Dialog 238877', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Medium'),
('Samsung 155129', 'Alice', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Low'),
('Asuz 891839', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Critical'),
('Samsung 832256', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Medium'),
('Cisco 623802', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Low'),
('Asuz 829031', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Critical'),
('Dialog 281935', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Medium'),
('Samsung 530557', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Low'),
('Samsung 174386', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Critical'),
('Dialog 696644', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Medium'),
('Asuz 234292', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Low'),
('Dialog 874939', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Critical'),
('Asuz 772021', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Medium'),
('Samsung 164546', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Low'),
('Samsung 233096', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Critical'),
('Samsung 108761', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Medium'),
('Samsung 977427', 'Alice', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Low'),
('Cisco 827554', 'John', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Critical'),
('Asuz 943079', 'John', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Medium'),
('Asuz 519975', 'John', '2 integrated 10/100/1000 Ethernet ports', '1st floor', 'Low'),
('Cisco 956996', 'John', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Critical'),
('Samsung 7283', 'John', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Medium'),
('Cisco 952971', 'John', '2 integrated 10/100/1000 Ethernet ports', 'corner office', 'Low'),
('Cisco 470636', 'John', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Critical'),
('Asuz 956076', 'John', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Medium'),
('Samsung 903965', 'John', '2 integrated 10/100/1000 Ethernet ports', '2nd floor', 'Low'),
('Samsung 68582', 'John', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Critical'),
('Asuz 660792', 'John', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Medium'),
('Cisco 441873', 'John', '2 integrated 10/100/1000 Ethernet ports', 'basement', 'Low'),
('Cisco 926399', 'John', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Critical'),
('Samsung 419313', 'John', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Medium'),
('Dialog 832786', 'John', '2 integrated 10/100/1000 Ethernet ports', 'rooftop', 'Low'),
('Samsung 978572', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Critical'),
('Samsung 398639', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Medium'),
('Cisco 647393', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '1st floor', 'Low'),
('Samsung 756143', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Critical'),
('Dialog 59601', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Medium'),
('Samsung 581949', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'corner office', 'Low'),
('Samsung 419324', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Critical'),
('Cisco 471833', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Medium'),
('Samsung 978318', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', '2nd floor', 'Low'),
('Dialog 154343', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Critical'),
('Cisco 535059', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Medium'),
('Samsung 76182', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'basement', 'Low'),
('Dialog 17020', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Critical'),
('Samsung 91594', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Medium'),
('Dialog 727610', 'John', '2 enhanced High-Speed WAN Interface Card slots that can host 2 single wide or 1 double wide and 1 Single wide (e)HWIC', 'rooftop', 'Low'),
('Dialog 580661', 'John', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Critical'),
('Asuz 613061', 'John', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Medium'),
('Dialog 70980', 'John', '1 Internal Services1 Internal Services Module slot', '1st floor', 'Low'),
('Cisco 914936', 'John', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Critical'),
('Dialog 224458', 'John', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Medium'),
('Dialog 664861', 'John', '1 Internal Services1 Internal Services Module slot', 'corner office', 'Low'),
('Asuz 276083', 'John', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Critical'),
('Asuz 861682', 'John', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Medium'),
('Cisco 649246', 'John', '1 Internal Services1 Internal Services Module slot', '2nd floor', 'Low'),
('Dialog 810342', 'John', '1 Internal Services1 Internal Services Module slot', 'basement', 'Critical'),
('Asuz 876463', 'John', '1 Internal Services1 Internal Services Module slot', 'basement', 'Medium'),
('Samsung 153170', 'John', '1 Internal Services1 Internal Services Module slot', 'basement', 'Low'),
('Cisco 198088', 'John', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Critical'),
('Samsung 3395', 'John', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Medium'),
('Cisco 284328', 'John', '1 Internal Services1 Internal Services Module slot', 'rooftop', 'Low'),
('Samsung 452493', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Critical'),
('Samsung 705986', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Medium'),
('Asuz 369221', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '1st floor', 'Low'),
('Dialog 264969', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Critical'),
('Samsung 674680', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Medium'),
('Dialog 343601', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'corner office', 'Low'),
('Samsung 235141', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Critical'),
('Asuz 270011', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Medium'),
('Cisco 997700', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', '2nd floor', 'Low'),
('Samsung 893728', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Critical'),
('Cisco 409295', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Medium'),
('Samsung 963295', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'basement', 'Low'),
('Asuz 723355', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Critical'),
('Cisco 521626', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Medium'),
('Cisco 24309', 'John', 'Fully integrated power distribution to modules supporting 802.3af Power over Ethernet (PoE) and Cisco Enhanced PoE', 'rooftop', 'Low'),
('Dialog 734523', 'John', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Critical'),
('Asuz 902421', 'John', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Medium'),
('Dialog 1441', 'John', 'Security Embedded hardware-accelerated VPN encryption', '1st floor', 'Low'),
('Dialog 746254', 'John', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Critical'),
('Cisco 290117', 'John', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Medium'),
('Cisco 627190', 'John', 'Security Embedded hardware-accelerated VPN encryption', 'corner office', 'Low'),
('Dialog 286264', 'John', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Critical'),
('Samsung 471740', 'John', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Medium'),
('Dialog 184623', 'John', 'Security Embedded hardware-accelerated VPN encryption', '2nd floor', 'Low'),
('Asuz 874148', 'John', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Critical'),
('Dialog 776433', 'John', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Medium'),
('Samsung 610217', 'John', 'Security Embedded hardware-accelerated VPN encryption', 'basement', 'Low'),
('Asuz 147248', 'John', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Critical'),
('Samsung 58919', 'John', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Medium'),
('Dialog 914330', 'John', 'Security Embedded hardware-accelerated VPN encryption', 'rooftop', 'Low'),
('Cisco 340606', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Critical'),
('Dialog 170577', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Medium'),
('Cisco 59883', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '1st floor', 'Low'),
('Samsung 25277', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Critical'),
('Samsung 672963', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Medium'),
('Asuz 359463', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'corner office', 'Low'),
('Samsung 43226', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Critical'),
('Samsung 652455', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Medium'),
('Samsung 10111', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', '2nd floor', 'Low'),
('Asuz 101500', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Critical'),
('Dialog 244924', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Medium'),
('Cisco 951016', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'basement', 'Low'),
('Dialog 234695', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Critical'),
('Dialog 404764', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Medium'),
('Asuz 720941', 'John', 'Secure collaborative communications with Group Encrypted Transport VPN, Dynamic Multipoint VPN, Enhanced Easy VPN', 'rooftop', 'Low'),
('Samsung 909503', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Critical'),
('Dialog 783737', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Medium'),
('Dialog 604946', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '1st floor', 'Low'),
('Cisco 458184', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Critical'),
('Cisco 510661', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Medium'),
('Asuz 464985', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'corner office', 'Low'),
('Samsung 294402', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Critical'),
('Asuz 337928', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Medium'),
('Asuz 190804', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', '2nd floor', 'Low'),
('Samsung 749282', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Critical'),
('Cisco 841826', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Medium'),
('Cisco 188051', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'basement', 'Low'),
('Asuz 135415', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Critical'),
('Dialog 530323', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Medium'),
('Asuz 294086', 'John', 'Integrated threat control using Cisco IOS Firewall, Cisco IOS Zone-Based Firewall, Cisco IOS IPS, Cisco IOS Content Filtering', 'rooftop', 'Low'),
('Cisco 775106', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Critical'),
('Cisco 528498', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Medium'),
('Asuz 262328', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '1st floor', 'Low'),
('Samsung 308690', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Critical'),
('Dialog 747863', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Medium'),
('Cisco 599437', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'corner office', 'Low'),
('Samsung 342467', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Critical'),
('Cisco 756029', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Medium'),
('Cisco 293175', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', '2nd floor', 'Low'),
('Cisco 580519', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Critical'),
('Asuz 671964', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Medium'),
('Samsung 492808', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'basement', 'Low'),
('Asuz 922392', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Critical'),
('Samsung 156082', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Medium'),
('Cisco 159195', 'John', 'Identity management that uses authentication, authorization, and accounting (AAA), and public key infrastructure something', 'rooftop', 'Low');